/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { };

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Form: typeof import('@/lib/Form.vue')['default'];
    FormItem: typeof import('@/lib/FormItem.vue')['default'];
    Input: typeof import('@/lib/Input.vue')['default'];
    Button: typeof import('@/lib/Button.vue')['default'];
  }
}

