/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('@/lib/Button.vue')['default']
    Dialog: typeof import('./components/Dialog/index.vue')['default']
    Form: typeof import('@/lib/Form.vue')['default']
    FormItem: typeof import('@/lib/FormItem.vue')['default']
    Input: typeof import('@/lib/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar/index.vue')['default']
  }
}
